### ISSUE TITLE
错误：查找字符串一节

### ISSUE THREAD

**Issue by mianhk** [52fhy/shell-book#6]
echo `expr index "$str" love` #最后一个参数是字符，字符串只保留首字母
此表达式不是只保留首字母，而是会对后面字符串每一个单独查找，返回最靠前的index。可能是l正好时最靠前的，所以没有在意。换成这个就好识别一点
echo `expr index "hello world" worl` #3

**Comment by 52fhy** [comment]
感谢，已修正。
