### ISSUE TITLE
函数篇是不是有问题

### ISSUE THREAD

**Issue by standingman** [52fhy/shell-book#7]
![image](https://user-images.githubusercontent.com/25574557/71538585-9c123d00-2968-11ea-9280-a6e80d8419a6.png)

**Comment by 52fhy** [comment]
什么问题

**Comment by chow-007** [comment]
> 

echo的是函数名，不是返回值，你这正好函数名和返回值一样了，你把返回值改成任意字符串（不要和函数名相同），你就知道了

**Comment by Glen-Y** [comment]
您说的是哪个


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "52fhy/shell-book"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月18日(星期五) 上午10:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [52fhy/shell-book] 函数篇是不是有问题 (#7)





   
echo的是函数名，不是返回值，你这正好函数名和返回值一样了，你把返回值改成任意字符串（不要和函数名相同），你就知道了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 52fhy** [comment]
> > 
> 
> echo的是函数名，不是返回值，你这正好函数名和返回值一样了，你把返回值改成任意字符串（不要和函数名相同），你就知道了

是有问题，已更新。参考：How to Return a String from Bash Functions
https://linuxhint.com/return-string-bash-functions/
